### ISSUE TITLE
Introduce a hierarchy?

### ISSUE THREAD

**Issue by jezdean** [carlosperate/awesome-microbit#18]
What are your thoughts on having a hierarchy now the list has gotten much larger? I've attached an example below. 

### Visual Languages
- 1
- 2
- 3

### Written Languages
- 1
- 2
- 3

### Online Editors
- 1
- 2
- 3

### Desktop Editors
- 1
- 2
- 3

### Programming Tools
- 1
- 2
- 3
### Python Libraries
- 1
- 2
- 3
### node.js Libraries
- 1
- 2
- 3

**Comment by carlosperate** [comment]
Hi Jez,

Yes, I'm quite open to introduce something like that. Until now I felt a flat structure was okay for the number of items in the list, but if it continues to grow (which it should :) then this type of reorganisation would be a good idea.
I must admit that right now I'm a bit busy with other stuff and it is not very high in my list of priorities, but if you have a suggestion for a full hierarchy with all the sections a I would love to hear about it :)

**Comment by jezdean** [comment]
That's awesome; I'll put in a pull request.

Do you have any particualar conventions you wish me to follow for the organisation?

**Comment by carlosperate** [comment]
Thanks, a PR would be quite appreciated!
There is definitely more than one way of doing it, which is probably why I haven't put the effort yet. Maybe to be safe we could quickly discuss it here before getting the PR ready, that way it'd be a lot easier to move things around if needed.

**Comment by jezdean** [comment]
Great idea-- something like:

## Programming

### Python
* [Documentation](url)
#### Editors
* 1
* 2
* 3
#### Libraries
* 1
* 2
* 3
#### Resources
* 1
* 2
* 3

### Javascript (PXT)
* [Documentation](url)
* [Online Editor](url)

#### Resources
* [PXT Source code](url)
* 2
* 3

### Other
* [Javascript (interpreted)](url)
*  [C/C++](url)


## Hardware
### Interface Chip
* 1
* 2
* 3
### General
* 1
* 2
* 3

## Further Reading (?)
### Articles
* 1
* 2
* 3
### Projects
* 1
* 2
* 3
### Websites
* 1
* 2
* 3
### Videos
* 1
* 2
* 3
### Teaching Resources
* 1
* 2
* 3

## Miscellaneous
* 1
* 2
* 3

**Comment by carlosperate** [comment]
Thanks Jez!
I would probably remove the "Further Reading" section, and make all its inner "level 2 subsections" a "level 1" so: 


## Programming

### Python
* [Documentation](url)
#### Editors
* 1
* 2
* 3
#### Libraries
* 1
* 2
* 3
#### Resources
* 1
* 2
* 3

### Javascript (PXT)
* [Documentation](url)
* [Online Editor](url)

#### Resources
* [PXT Source code](url)
* 2
* 3

### C/C++
* 1
* 2
* 3

### Other
* [Javascript (interpreted)](url)
*  [C/C++](url)


## Hardware
### Interface Chip
* 1
* 2
* 3
### General
* 1
* 2
* 3

## Articles
* 1
* 2
* 3
## Projects
* 1
* 2
* 3
## Websites
* 1
* 2
* 3
## Videos
* 1
* 2
* 3
## Teaching Resources
* 1
* 2
* 3

## Miscellaneous
* 1
* 2
* 3
