### ISSUE TITLE
Lisp on the BBC Micro Bit

### ISSUE THREAD

**Issue by technoblogy** [carlosperate/awesome-microbit#180]
Hi Carlos, you might want to include my Lisp interpreter for the BBC Micro Bit:

`http://www.ulisp.com/show?2672`

**Comment by carlosperate** [comment]
Yeah, that looks awesome!
If you'd like to prepare a PR I'd be happy to merge it!

One note, looking at the instructions from that list it's not clear how to download and upload the uLisp sketch into the micro:bit.
Even looking at the http://www.ulisp.com/show?19XT article linked I still coudn't find the steps to locate the sketch. Could you add that step to http://www.ulisp.com/show?2672?

**Comment by technoblogy** [comment]
Hi Carlos,

> Yeah, that looks awesome!
> If you'd like to prepare a PR I'd be happy to merge it!

Thanks; here it is:

Under section:

Other micro:bit Languages
Other programming languages capable to program the micro:bit.

Lisp - An interpreter for the classic AI programming language for the BBC micro:bit.

Link to: http://www.ulisp.com/show?2672

> One note, looking at the instructions from that list it's not clear how to download and upload the uLisp sketch into the micro:bit.
> Even looking at the http://www.ulisp.com/show?19XT article linked I still coudn't find the steps to locate the sketch. Could you add that step to http://www.ulisp.com/show?2672?

Good suggestion; I’ve added a line to clarify that.

Regards,
David

PS I’m in Cambridge too!

+------------------------------------------------------------+
David Johnson-Davies, Human-Computer Interface Ltd
17 Signet Court, Swanns Road, Cambridge, CB5 8LA, England.

Tel: +44 1223 314934, Fax: +44 1223 462562
Email: david@interface.co.uk, Web: http://www.interface.co.uk/
+------------------------------------------------------------+

**Comment by carlosperate** [comment]
Thanks @technoblogy! I've created PR #181 

P.S.: What a small world :)

**Comment by carlosperate** [comment]
Closing this one as it has been implemented in #181.
Thanks @technoblogy for sharing!
