### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by bestony** [carlosperate/awesome-microbit#255]
this link is wrong.

- Debugging the micro:bit with pyOCD and GDB - Shows how to debug a micro:bit program using PyOCD and GDB.

this  link is Mbed OS 5 , Not a pyOCD Guide.

**Comment by carlosperate** [comment]
Looks like Arm has removed the article (https://docs.mbed.com/docs/mbed-os-handbook/en/5.4/debugging/debugging_microbit/) and redirected to https://os.mbed.com/docs/mbed-os/v5.11/introduction/index.html :(

I'll see if I can find the original article somewhere else, thanks @bestony!

**Comment by carlosperate** [comment]
Found it: https://os.mbed.com/docs/mbed-os/v5.11/tutorials/debug-microbit.html

@bestony since you've found the issue, would you like to submit a PR as well? I'm happy to help with that or change it myself, whatever you prefer :)

**Comment by carlosperate** [comment]
I've also opened an issue here to see if the URL redirect can be fixed: https://github.com/ARMmbed/mbed-os-5-docs/issues/1005

Nevertheless we should have a direct link to the latest version of the article, rather than depend on redirects.

**Comment by bestony** [comment]
i will open a pull request 😄

**Comment by bestony** [comment]
PR #256

**Comment by carlosperate** [comment]
Fantastic, thanks @bestony!
