### ISSUE TITLE
BBC teaching lesssons still working ? 

### ISSUE THREAD

**Issue by selmen2004** [carlosperate/awesome-microbit#258]
Hi 
I can load 
http://www.bbc.co.uk/programmes/articles/2M3H2YpKLsw2W8fC2ycHYSR/welcome-to-the-micro-bit-live-lesson
but when I click Play to watch the session , I am redirected to : 
https://www.bbc.co.uk/programmes/p03lxrcj
that redirects to :
https://www.bbc.com/teach/live-lessons
Is this only for me or happens to UK residents too ? (tried UK proxy with no luck too )

**Comment by carlosperate** [comment]
I get the same redirect in the UK :(
