### ISSUE TITLE
Some micro:bit MakeCode extensions

### ISSUE THREAD

**Issue by alankrantas** [carlosperate/awesome-microbit#295]
Hi,

Please consider adding these extensions if you have time. You does a great job maintaining the list and it helped me a lot.

For DHT11/DHT22 temperature and humidity sensors
https://github.com/alankrantas/pxt-DHT11_DHT22

For ESP8266 (ESP-01) and ThingSpeak
https://github.com/alankrantas/pxt-ESP8266_ThingSpeak

For TCS3200 color sensors
https://github.com/DoraLC/pxt-tcs3200-color-sensor

For IR transmitter/receiver modules
https://github.com/lioujj/pxt-IR

**Comment by carlosperate** [comment]
Hi @alankrantas,

Yes, these look like good additions! Could you submit individual PRs for each one of these?

**Comment by alankrantas** [comment]
I'll fork this repository and send pull requests . I'm still not so familiar with PRs. So I should send one at a time and wait for you to merge it, or can I send all of them at once?

**Comment by carlosperate** [comment]
Either way works for me, I'm happy to walk you through the process and fix any possible conflicts if you raise all the PRs at the same time.
Let me know if you have any questions and thank you for your contributions!

**Comment by alankrantas** [comment]
Alright, I'll do one at a time, no hurry.
