### ISSUE TITLE
Looking for library for ds18b20  temperature sensor

### ISSUE THREAD

**Issue by G-Boronad** [carlosperate/awesome-microbit#530]
Hello,
I'm looking for a python library for the ds18b20 temperature sensor that would work with a micro:bit V2.
Do you know if it exists?
Thank you in advance for your help.
G.B.

**Comment by carlosperate** [comment]
I haven't seen one for micro:bit MicroPython yet, only this one for MakeCode:

https://github.com/carlosperate/awesome-microbit/blob/515b59818bc716eb7bd77ceb9f19a1b9139aaad4/README.md#L198

Maybe you can use it as a reference to create a MicroPython library? I'd be happy to add it to the list if you make one or find one!
