### ISSUE TITLE
Bug - grammatical error in README.md

### ISSUE THREAD

**Issue by ayushrakesh** [carlosperate/awesome-microbit#613]
I have noticed one grammatical mistake in inside section "**Visual Programming**"

"**MicroCode is a icon-based**"  should be "**MicroCode is an icon-based**"

Please assign this task to me.

**Comment by carlosperate** [comment]
Thanks @ayushrakesh!  If you are happy to create a PR we can merge it right away :)

**Comment by hemangtk** [comment]
Hey @carlosperate i can see that this issue isn't fixed yet could you please assign me this issue so that I can fix it right away

**Comment by hemangtk** [comment]
Hey @carlosperate just fixed the issue 
please do give it quick check let me know if theres any more changes required
Thank you!!

**Comment by carlosperate** [comment]
Thanks @hemangtk and @ayushrakesh! This has been implemented in https://github.com/carlosperate/awesome-microbit/pull/634.
